### ISSUE TITLE
Some links redirect to AGH extranet

### ISSUE THREAD

**Issue by qepasa** [mkrzywda/MKKnowledgeGraph#10]
For example in [Upcoming.md](https://github.com/mkrzywda/MKKnowledgeGraph/blob/main/Upcoming.md) you have a link to [Data Mining of Popular Science Books Based on Web Crawler ](https://ieeexplore-1ieee-1org-1000047u50047.wbg2.bg.agh.edu.pl/document/9196238) which redirects to AGH extranet (screenshot attached)

<img src="https://user-images.githubusercontent.com/18561325/103139685-fa3e4100-46de-11eb-836d-2b4e8e41f873.png" width="400">

**Proposed solution:**
Replace with direct links e.g. [https://ieeexplore.ieee.org/abstract/document/9196238](https://ieeexplore.ieee.org/abstract/document/9196238) for aforementioned article.

**Comment by mkrzywda** [comment]
Thanks :) Fix in last PR.
